version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: my_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: event_planner_db
    volumes:
      - ./mongo-init/init.js:/docker-entrypoint-initdb.d/init.js:ro  # ✅ Ensure this is here
    networks:
      - my_network


  springboot-app:
    build: ./spring-boot  # ✅ Ensure this points to the spring-boot directory
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongodb:27017/event_planner_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - my_network


  frontend:
    build: ./frontend
    container_name: vite-frontend
    restart: always
    ports:
      - "5173:5173"  # ✅ Expose Vite dev server
    depends_on:
      - springboot-app
    networks:
      - my_network


networks:
  my_network:
